// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hgbktacdwybydcycppsf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhnYmt0YWNkd3lieWRjeWNwcHNmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzMjY0MTIsImV4cCI6MjA2NzkwMjQxMn0.H6_tlGE1N677IJT8xP1XqAJM5UxkDx5igFifKy9wgqo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});